# Generated by Django 2.0.4 on 2018-08-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='NDC',
            field=models.CharField(help_text='The national drug code for the product. US Only.', max_length=12, null=True, verbose_name='NDC'),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='NDC_pattern',
            field=models.CharField(choices=[('4-4-2', '4-4-2'), ('5-3-2', '5-3-2'), ('5-4-1', '5-4-1')], help_text='The pattern of the NDC.  US Only.  Optional.', max_length=5, null=True, verbose_name='NDC_pattern'),
        ),
    ]
