# Generated by Django 2.1.5 on 2019-03-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_masterdata', '0002_auto_20180821_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
