# Generated by Django 2.0.4 on 2019-06-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_masterdata', '0004_tradeitem_serial_number_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeitem',
            name='pack_count',
            field=models.PositiveIntegerField(help_text='The number of items packed into this package (where appropriate).', null=True, verbose_name='Pack Count'),
        ),
    ]
