# Generated by Django 3.0.3 on 2020-02-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_masterdata', '0008_outboundmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='outboundmapping',
            options={'ordering': ['company__name'], 'verbose_name': 'Outbound Mapping', 'verbose_name_plural': 'Outbound Mappings'},
        ),
        migrations.AlterModelOptions(
            name='tradeitem',
            options={'ordering': ['regulated_product_name'], 'verbose_name': 'Trade Item', 'verbose_name_plural': 'Trade Items'},
        ),
    ]
